### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by FerbFloo** [Lunastellia/Challenger-Among-Us#3]
Yeah, i just found this mod(pack) on amodsus and would love to try it out with a couple of friends! Will you update the mod to the newest version (2021.4.14s i believe) or is it dead?

anyways tysm for making it!

**Comment by Lunastellia** [comment]
Hi,  for the moment there are no plans to upgrade to a 12.4 / 14.4 update. I will wait for the next major update of the game, version 3.31.3s is rather stable and I prefer to keep it that way

you can play on the version via challenger / matux servers in 3.31.3s without worries with the game client download via the launcher
