### ISSUE TITLE
Challenger mod not working

### ISSUE THREAD

**Issue by Nikeeey** [Lunastellia/Challenger-Among-Us#4]
It keeps saying unknow error please try again. If the issue remains please contact support when i press install. Please help

**Comment by Lunastellia** [comment]
hello, I am aware that the current launcher bug, I am working with Matux (modManager) for the design of a new more efficient launcher / updator which will make it easier to download the game) while waiting for you to download the latest version of the game on the link below, be careful however this latest version has a lot of bugs, the next update which fixes a lot of bugs is coming soon.


https://www.mediafire.com/file/dl0xyjopbio8g59/Challenger1.4.1.zip/file
