### ISSUE TITLE
challenger 1 server, telling me to update but challenger 2 not

### ISSUE THREAD

**Issue by SAB236YT** [Lunastellia/Challenger-Among-Us#7]
how do i fix this?

**Comment by Lunastellia** [comment]
Use Challenger 2 server to play  (version 4.3.2) ! ... I have update challenger 1 sever for (private alpha 5.0.0)

**Comment by SAB236YT** [comment]
> Use Challenger 2 server to play (version 4.3.2) ! ... I have update challenger 1 sever for (private alpha 5.0.0)

but also no one joins.
